apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - components/config-custom-runtimes
  - components/config-hw-profile

resources:
  - dsc.yaml
  - dsci.yaml
  - odh-dashboard.yaml
