apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - components/config-custom-runtimes
  - components/config-hw-profile
  - components/spyre-hw-profile
  - components/basic-hw-profile

resources:
  - dsc.yaml
  - dsci.yaml
  - odh-dashboard.yaml
  # - fix-kubeadmin.yaml
