apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/authorino-operator/operator/overlays/stable?ref=v0.20

  # oc kustomize https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/authorino-operator/operator/overlays/stable?ref=v0.20
  - operator.yaml
